spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:?createDatabaseIfNotExist=true&useSSL=false
      username: 
      password: 
  #session-timeout是session的持续时间，86400表示一天
  session:
    timeout: 86400
server:
  address: 0.0.0.0
